use_case: "customer support chatbot for Acme Corp"
risk_tolerance:
  deploy_threshold: 0.10
  warn_threshold: 0.25
  reject_threshold: 0.30
evaluation:
  num_prompts: 20
  prompt_categories: [factual_recall, edge_cases, policy_boundaries, ambiguous_queries]
doc_sources:
  - type: local
    path: ./docs/policies/
model:
  provider: bedrock
  model_id: "apac.anthropic.claude-sonnet-4-20250514-v1:0"
elasticsearch:
  host: "http://localhost:9200"
  index: "trusted_docs"
